name: Run Build and Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v2

      - name: 💡 Perform Common Steps 💡
        uses: ./.github/workflows/common

      - name: 🛠 Build Solution 🛠
        shell: bash
        run: dotnet build

      - name: ✅ Run Unit Tests ✅
        shell: bash
        run: dotnet test

      - name: 📦 Cache SonarCloud Packages 📦
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.cs') }}
          restore-keys: ${{ runner.os }}-sonar-

      - name: 🌐 SonarCloud Setup 🌐
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 📊 SonarCloud Analysis 📊
        shell: bash
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"personal-public-repos_algorithms-and-data-structures" /o:"personal-public-repos" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"